In [16]:
%run utils.ipynb

In [2]:
tech = ['HCLTECH', 'WIPRO', 'INFY', 'TCS', 'TECHM']
banks = ['HDFCBANK', 'ICICIBANK', 'SBIN', 'KOTAKBANK', 'AXISBANK', 'FEDERALBNK', 'KARURVYSYA', 'CANBK']
others = ['RELIANCE', 'HINDUNILVR', 'ITC', 'M&M', 'TATAMOTORS', 'TATASTEEL', 'CIPLA']

_all = tech + banks + others

nifty_50_stocks = ['EICHERMOT','HEROMOTOCO','NESTLEIND','ONGC','BAJAJ-AUTO','TATASTEEL','GRASIM',
                   'BRITANNIA','BAJFINANCE','DIVISLAB','M&M','HINDUNILVR','HDFCBANK','HDFCLIFE','BHARTIARTL','TCS',
                   'LT','DRREDDY','ULTRACEMCO','SUNPHARMA','NTPC','TATAMOTORS','UPL','SBIN','HINDALCO','ITC','JSWSTEEL',
                   'COALINDIA','RELIANCE','BPCL','LTIM','MARUTI','HCLTECH','POWERGRID','WIPRO','SBILIFE','AXISBANK',
                   'ADANIPORTS','ICICIBANK','TITAN','BAJAJFINSV','KOTAKBANK','TATACONSUM','APOLLOHOSP','INFY','ASIANPAINT',
                   'ADANIENT','INDUSINDBK','TECHM','CIPLA',]

In [3]:
final_df = pd.concat([analyse(i, save_to_disk=True)[0] for i in nifty_50_stocks]).reset_index(drop=True)

In [4]:
final_df

,10_cross_30,MACD_Signal_MACD,MACD_lim,abv_50,abv_200,actual_returns,proba,stock
0,1,0,0,0,0,3.43,0.76,EICHERMOT
1,1,0,1,0,0,2.89,0.83,EICHERMOT
2,1,0,0,1,0,2.79,0.72,EICHERMOT
3,0,1,0,1,1,0.53,1.00,HEROMOTOCO
4,0,1,1,0,0,2.54,0.83,NESTLEIND
...,...,...,...,...,...,...,...,...
162,0,1,1,1,1,2.72,0.66,ADANIENT
163,0,1,0,1,0,8.35,1.00,INDUSINDBK
164,1,1,0,1,0,7.83,1.00,INDUSINDBK
165,0,1,1,0,0,2.37,0.78,TECHM
166,1,0,0,0,1,1.17,0.71,TECHM

In [5]:
summary = final_df.groupby(['10_cross_30', 'MACD_Signal_MACD', 'MACD_lim', 'abv_50', 'abv_200']).agg(
    avg_return = ('actual_returns', 'mean'),
    median_return = ('actual_returns', 'median'),
    avg_probability = ('proba', 'mean'),
    stocks = ('stock', 'unique'),
    stock_count = ('stock', 'count')
)

summary.sort_values(by=['stock_count', 'avg_probability', 'avg_return'], ascending=False)

                                                      avg_return  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
1           0                1        0      0          3.266471
0           1                0        1      0          4.388571
1           0                1        0      1          2.516154
0           1                0        1      1          4.053333
                             1        1      0          2.801818
1           0                0        0      0          2.305455
            1                0        0      1          2.437273
                                             0          1.939000
                                      1      0          4.900000
            0                0        0      1          1.926667
0           1                1        1      1          1.762222
1           0                0        1      0          2.085000
                                             1          1.544286
0           1                1        0      0          2.946667
                                             1          1.496667
1           1                1        0      0          2.724000
                             0        1      1          5.962500
            0                1        1      0          2.005000
            1                1        1      0          2.240000
                                      0      1          1.990000
0           1                0        0      0          2.260000

                                                      median_return  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
1           0                1        0      0                3.120
0           1                0        1      0                4.465
1           0                1        0      1                2.300
0           1                0        1      1                3.900
                             1        1      0                2.090
1           0                0        0      0                2.070
            1                0        0      1                2.040
                                             0                1.680
                                      1      0                5.110
            0                0        0      1                1.640
0           1                1        1      1                1.770
1           0                0        1      0                2.010
                                             1                0.790
0           1                1        0      0                2.680
                                             1                1.435
1           1                1        0      0                2.250
                             0        1      1                6.175
            0                1        1      0                2.005
            1                1        1      0                2.240
                                      0      1                1.990
0           1                0        0      0                2.260

                                                      avg_probability  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
1           0                1        0      0               0.828824
0           1                0        1      0               0.970000
1           0                1        0      1               0.727692
0           1                0        1      1               0.941667
                             1        1      0               0.806364
1           0                0        0      0               0.761818
            1                0        0      1               0.735455
                                             0               0.688000
                                      1      0               0.920000
            0                0        0      1               0.746667
0           1                1        1      1               0.698889
1           0                0        1      0               0.760000
                                             1               0.715714
0           1                1        0      0               0.770000
                                             1               0.693333
1           1                1        0      0               0.680000
                             0        1      1               1.000000
            0                1        1      0               0.685000
            1                1        1      0               0.670000
                                      0      1               0.670000
0           1                0        0      0               0.660000

                                                                                                 stocks  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
1           0                1        0      0        [EICHERMOT, NESTLEIND, DIVISLAB, HDFCLIFE, BHA...
0           1                0        1      0        [TATASTEEL, BRITANNIA, HINDUNILVR, HDFCLIFE, B...
1           0                1        0      1        [ONGC, BHARTIARTL, TCS, NTPC, UPL, LTIM, HCLTE...
0           1                0        1      1        [HEROMOTOCO, DRREDDY, ULTRACEMCO, NTPC, SBIN, ...
                             1        1      0        [TATASTEEL, BRITANNIA, ULTRACEMCO, SUNPHARMA, ...
1           0                0        0      0        [EICHERMOT, ONGC, M&M, HDFCBANK, DRREDDY, ITC,...
            1                0        0      1        [NESTLEIND, BAJFINANCE, HDFCBANK, NTPC, SBIN, ...
                                             0        [ONGC, DIVISLAB, ULTRACEMCO, LTIM, MARUTI, HCL...
                                      1      0        [ONGC, GRASIM, M&M, HINDUNILVR, TATAMOTORS, JS...
            0                0        0      1        [TCS, DRREDDY, UPL, RELIANCE, MARUTI, WIPRO, S...
0           1                1        1      1        [BAJAJ-AUTO, TATASTEEL, TCS, JSWSTEEL, RELIANC...
1           0                0        1      0        [EICHERMOT, BAJAJ-AUTO, BRITANNIA, HINDUNILVR,...
                                             1        [BAJAJ-AUTO, DIVISLAB, LT, DRREDDY, ITC, MARUT...
0           1                1        0      0        [NESTLEIND, BAJAJ-AUTO, TATAMOTORS, ITC, BAJAJ...
                                             1        [BAJFINANCE, TCS, TATAMOTORS, COALINDIA, MARUT...
1           1                1        0      0        [NESTLEIND, BAJFINANCE, LTIM, AXISBANK, BAJAJF...
                             0        1      1                       [HINDUNILVR, UPL, HINDALCO, TITAN]
            0                1        1      0                                 [ULTRACEMCO, ASIANPAINT]
            1                1        1      0                                             [ASIANPAINT]
                                      0      1                                               [HDFCLIFE]
0           1                0        0      0                                               [HDFCLIFE]

                                                      stock_count
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
1           0                1        0      0                 17
0           1                0        1      0                 14
1           0                1        0      1                 13
0           1                0        1      1                 12
                             1        1      0                 11
1           0                0        0      0                 11
            1                0        0      1                 11
                                             0                 10
                                      1      0                  9
            0                0        0      1                  9
0           1                1        1      1                  9
1           0                0        1      0                  8
                                             1                  7
0           1                1        0      0                  6
                                             1                  6
1           1                1        0      0                  5
                             0        1      1                  4
            0                1        1      0                  2
            1                1        1      0                  1
                                      0      1                  1
0           1                0        0      0                  1

In [6]:
signal_grade = pd.qcut(summary['stock_count'].rename('signal_grade'), 4, labels=['grade D', 'grade C', 'grade B', 'grade A'])

summary = summary.merge(signal_grade, how='left', left_index=True, right_index=True)

In [7]:
summary = summary[summary['signal_grade'].isin(['grade A', 'grade B', 'grade C'])]

summary['expected_return'] = round(0.5 * (summary['avg_return'] + summary['median_return']), 3)

summary

                                                      avg_return  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
0           1                0        1      0          4.388571
                                             1          4.053333
                             1        0      0          2.946667
                                             1          1.496667
                                      1      0          2.801818
                                             1          1.762222
1           0                0        0      0          2.305455
                                             1          1.926667
                                      1      0          2.085000
                                             1          1.544286
                             1        0      0          3.266471
                                             1          2.516154
            1                0        0      0          1.939000
                                             1          2.437273
                                      1      0          4.900000

                                                      median_return  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
0           1                0        1      0                4.465
                                             1                3.900
                             1        0      0                2.680
                                             1                1.435
                                      1      0                2.090
                                             1                1.770
1           0                0        0      0                2.070
                                             1                1.640
                                      1      0                2.010
                                             1                0.790
                             1        0      0                3.120
                                             1                2.300
            1                0        0      0                1.680
                                             1                2.040
                                      1      0                5.110

                                                      avg_probability  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
0           1                0        1      0               0.970000
                                             1               0.941667
                             1        0      0               0.770000
                                             1               0.693333
                                      1      0               0.806364
                                             1               0.698889
1           0                0        0      0               0.761818
                                             1               0.746667
                                      1      0               0.760000
                                             1               0.715714
                             1        0      0               0.828824
                                             1               0.727692
            1                0        0      0               0.688000
                                             1               0.735455
                                      1      0               0.920000

                                                                                                 stocks  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
0           1                0        1      0        [TATASTEEL, BRITANNIA, HINDUNILVR, HDFCLIFE, B...
                                             1        [HEROMOTOCO, DRREDDY, ULTRACEMCO, NTPC, SBIN, ...
                             1        0      0        [NESTLEIND, BAJAJ-AUTO, TATAMOTORS, ITC, BAJAJ...
                                             1        [BAJFINANCE, TCS, TATAMOTORS, COALINDIA, MARUT...
                                      1      0        [TATASTEEL, BRITANNIA, ULTRACEMCO, SUNPHARMA, ...
                                             1        [BAJAJ-AUTO, TATASTEEL, TCS, JSWSTEEL, RELIANC...
1           0                0        0      0        [EICHERMOT, ONGC, M&M, HDFCBANK, DRREDDY, ITC,...
                                             1        [TCS, DRREDDY, UPL, RELIANCE, MARUTI, WIPRO, S...
                                      1      0        [EICHERMOT, BAJAJ-AUTO, BRITANNIA, HINDUNILVR,...
                                             1        [BAJAJ-AUTO, DIVISLAB, LT, DRREDDY, ITC, MARUT...
                             1        0      0        [EICHERMOT, NESTLEIND, DIVISLAB, HDFCLIFE, BHA...
                                             1        [ONGC, BHARTIARTL, TCS, NTPC, UPL, LTIM, HCLTE...
            1                0        0      0        [ONGC, DIVISLAB, ULTRACEMCO, LTIM, MARUTI, HCL...
                                             1        [NESTLEIND, BAJFINANCE, HDFCBANK, NTPC, SBIN, ...
                                      1      0        [ONGC, GRASIM, M&M, HINDUNILVR, TATAMOTORS, JS...

                                                      stock_count  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
0           1                0        1      0                 14
                                             1                 12
                             1        0      0                  6
                                             1                  6
                                      1      0                 11
                                             1                  9
1           0                0        0      0                 11
                                             1                  9
                                      1      0                  8
                                             1                  7
                             1        0      0                 17
                                             1                 13
            1                0        0      0                 10
                                             1                 11
                                      1      0                  9

                                                     signal_grade  \
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
0           1                0        1      0            grade A
                                             1            grade A
                             1        0      0            grade C
                                             1            grade C
                                      1      0            grade B
                                             1            grade C
1           0                0        0      0            grade B
                                             1            grade C
                                      1      0            grade C
                                             1            grade C
                             1        0      0            grade A
                                             1            grade A
            1                0        0      0            grade B
                                             1            grade B
                                      1      0            grade C

                                                      expected_return
10_cross_30 MACD_Signal_MACD MACD_lim abv_50 abv_200
0           1                0        1      0                  4.427
                                             1                  3.977
                             1        0      0                  2.813
                                             1                  1.466
                                      1      0                  2.446
                                             1                  1.766
1           0                0        0      0                  2.188
                                             1                  1.783
                                      1      0                  2.048
                                             1                  1.167
                             1        0      0                  3.193
                                             1                  2.408
            1                0        0      0                  1.810
                                             1                  2.239
                                      1      0                  5.005

In [8]:
cols = list(summary.index.names) + ['signal_grade', 'expected_return']

signals = summary.reset_index()[cols]

In [9]:
signals

,10_cross_30,MACD_Signal_MACD,MACD_lim,abv_50,abv_200,signal_grade,expected_return
0,0,1,0,1,0,grade A,4.427
1,0,1,0,1,1,grade A,3.977
2,0,1,1,0,0,grade C,2.813
3,0,1,1,0,1,grade C,1.466
4,0,1,1,1,0,grade B,2.446
5,0,1,1,1,1,grade C,1.766
6,1,0,0,0,0,grade B,2.188
7,1,0,0,0,1,grade C,1.783
8,1,0,0,1,0,grade C,2.048
9,1,0,0,1,1,grade C,1.167
10,1,0,1,0,0,grade A,3.193
11,1,0,1,0,1,grade A,2.408
12,1,1,0,0,0,grade B,1.810
13,1,1,0,0,1,grade B,2.239
14,1,1,0,1,0,grade C,5.005

In [10]:
TRADES = []
trade_in_progress = False
check_trend_change = False
holding_period = 10

for i in nifty_50_stocks:
    # _df = get_stock_info(i)
    _df = read_stock_info_from_disk(i)
    _df = add_signal_indicators(_df)

    _df['stock'] = i
    _df.reset_index().reset_index().apply(backtest_signals, axis=1)
    print(f'done performing backtesting for {i}')
    del _df
    trade_in_progress = False

done performing backtesting for EICHERMOT
done performing backtesting for HEROMOTOCO
done performing backtesting for NESTLEIND
done performing backtesting for ONGC
done performing backtesting for BAJAJ-AUTO
done performing backtesting for TATASTEEL
done performing backtesting for GRASIM
done performing backtesting for BRITANNIA
done performing backtesting for BAJFINANCE
done performing backtesting for DIVISLAB
done performing backtesting for M&M
done performing backtesting for HINDUNILVR
done performing backtesting for HDFCBANK
done performing backtesting for HDFCLIFE
done performing backtesting for BHARTIARTL
done performing backtesting for TCS
done performing backtesting for LT
done performing backtesting for DRREDDY
done performing backtesting for ULTRACEMCO
done performing backtesting for SUNPHARMA
done performing backtesting for NTPC
done performing backtesting for TATAMOTORS
done performing backtesting for UPL
done performing backtesting for SBIN
done performing backtesting for HINDALCO
done performing backtesting for ITC
done performing backtesting for JSWSTEEL
done performing backtesting for COALINDIA
done performing backtesting for RELIANCE
done performing backtesting for BPCL
done performing backtesting for LTIM
done performing backtesting for MARUTI
done performing backtesting for HCLTECH
done performing backtesting for POWERGRID
done performing backtesting for WIPRO
done performing backtesting for SBILIFE
done performing backtesting for AXISBANK
done performing backtesting for ADANIPORTS
done performing backtesting for ICICIBANK
done performing backtesting for TITAN
done performing backtesting for BAJAJFINSV
done performing backtesting for KOTAKBANK
done performing backtesting for TATACONSUM
done performing backtesting for APOLLOHOSP
done performing backtesting for INFY
done performing backtesting for ASIANPAINT
done performing backtesting for ADANIENT
done performing backtesting for INDUSINDBK
done performing backtesting for TECHM
done performing backtesting for CIPLA

In [11]:
pd.DataFrame(TRADES).groupby('stock')['returns'].agg(['mean','median','sum','count']).reset_index()

         stock      mean  median      sum  count
0     ADANIENT  8.562442  1.4995  890.494    104
1   ADANIPORTS  1.403719  2.3100  134.757     96
2   APOLLOHOSP  1.075094  0.7870  149.438    139
3   ASIANPAINT  2.063376  1.4390  257.922    125
4     AXISBANK  0.615099  0.4090   80.578    131
5   BAJAJ-AUTO  0.917780  0.8680  100.038    109
6   BAJAJFINSV  1.118288  1.0050  124.130    111
7   BAJFINANCE  1.658000  2.2800  140.930     85
8   BHARTIARTL  1.146261  0.6280  136.405    119
9         BPCL  0.550776 -0.0095   73.804    134
10   BRITANNIA  0.468482 -0.1110   66.056    141
11       CIPLA  0.159120  0.4470   22.595    142
12   COALINDIA  0.031707  0.1950    2.917     92
13    DIVISLAB  1.500491  1.2880  162.053    108
14     DRREDDY  0.676986  0.9540   96.809    143
15   EICHERMOT  1.646960  1.5095  204.223    124
16      GRASIM  0.582194  0.3705   62.877    108
17     HCLTECH  1.263229  0.9530  165.483    131
18    HDFCBANK  1.016604  0.6570  141.308    139
19    HDFCLIFE  0.346515 -0.3180   11.435     33
20  HEROMOTOCO  0.582157  0.6490   73.934    127
21    HINDALCO  1.167947  1.4630  155.337    133
22  HINDUNILVR  1.418097  0.6190  190.025    134
23   ICICIBANK  1.112228  1.0990  136.804    123
24  INDUSINDBK  2.626465  1.6090  299.417    114
25        INFY  0.632699  1.0295   86.047    136
26         ITC  1.420750  0.9480  210.271    148
27    JSWSTEEL  1.625622  1.2660  193.449    119
28   KOTAKBANK  4.561099  0.2070  597.504    131
29          LT  1.781709  0.7470  183.516    103
30        LTIM  0.843088 -0.1580   28.665     34
31         M&M  0.085986  0.4350   12.468    145
32      MARUTI  1.296964  1.5230  143.963    111
33   NESTLEIND  1.195872  0.9910   93.278     78
34        NTPC  1.117376  0.6870  130.733    117
35        ONGC  1.043125  0.6960  150.210    144
36   POWERGRID  0.680690  0.2195   68.069    100
37    RELIANCE  1.409411  1.9470  198.727    141
38     SBILIFE  0.360359  0.8060   14.054     39
39        SBIN  0.966259  0.8940  134.310    139
40   SUNPHARMA  0.798924  0.9140  105.458    132
41  TATACONSUM  1.577029  1.1555  214.476    136
42  TATAMOTORS  0.428908 -0.2305   55.758    130
43   TATASTEEL  1.379455  0.9130  169.673    123
44         TCS  0.629929  1.6380   71.182    113
45       TECHM  1.184622  1.0910  106.616     90
46       TITAN  1.944967  0.7680  239.231    123
47  ULTRACEMCO  0.680531  0.1000   76.900    113
48         UPL  3.091076  0.7900  364.747    118
49       WIPRO  1.374131  0.9020  188.256    137

In [12]:
pd.DataFrame(TRADES)['returns'].agg(['mean','median','sum','count']).reset_index()

    index     returns
0    mean     1.32033
1  median     0.84400
2     sum  7717.33000
3   count  5845.00000

In [13]:
TRADES_WITHOUT_TREND_CHECK = [_ for _ in TRADES]

In [17]:
TRADES = []
trade_in_progress = False
check_trend_change = True
holding_period = 10

for i in nifty_50_stocks:
    # _df = get_stock_info(i)
    _df = read_stock_info_from_disk(i)
    _df = add_signal_indicators(_df)

    _df['stock'] = i
    _df.reset_index().reset_index().apply(backtest_signals, axis=1)
    print(f'done performing backtesting for {i}')
    del _df
    trade_in_progress = False

done performing backtesting for EICHERMOT
done performing backtesting for HEROMOTOCO
done performing backtesting for NESTLEIND
done performing backtesting for ONGC
done performing backtesting for BAJAJ-AUTO
done performing backtesting for TATASTEEL
done performing backtesting for GRASIM
done performing backtesting for BRITANNIA
done performing backtesting for BAJFINANCE
done performing backtesting for DIVISLAB
done performing backtesting for M&M
done performing backtesting for HINDUNILVR
done performing backtesting for HDFCBANK
done performing backtesting for HDFCLIFE
done performing backtesting for BHARTIARTL
done performing backtesting for TCS
done performing backtesting for LT
done performing backtesting for DRREDDY
done performing backtesting for ULTRACEMCO
done performing backtesting for SUNPHARMA
done performing backtesting for NTPC
done performing backtesting for TATAMOTORS
done performing backtesting for UPL
done performing backtesting for SBIN
done performing backtesting for HINDALCO
done performing backtesting for ITC
done performing backtesting for JSWSTEEL
done performing backtesting for COALINDIA
done performing backtesting for RELIANCE
done performing backtesting for BPCL
done performing backtesting for LTIM
done performing backtesting for MARUTI
done performing backtesting for HCLTECH
done performing backtesting for POWERGRID
done performing backtesting for WIPRO
done performing backtesting for SBILIFE
done performing backtesting for AXISBANK
done performing backtesting for ADANIPORTS
done performing backtesting for ICICIBANK
done performing backtesting for TITAN
done performing backtesting for BAJAJFINSV
done performing backtesting for KOTAKBANK
done performing backtesting for TATACONSUM
done performing backtesting for APOLLOHOSP
done performing backtesting for INFY
done performing backtesting for ASIANPAINT
done performing backtesting for ADANIENT
done performing backtesting for INDUSINDBK
done performing backtesting for TECHM
done performing backtesting for CIPLA

In [18]:
pd.DataFrame(TRADES).groupby('stock')['returns'].agg(['mean','median','sum','count']).reset_index()

         stock      mean  median      sum  count
0     ADANIENT  7.044971 -2.0045  972.206    138
1   ADANIPORTS  1.271306 -1.5270  153.828    121
2   APOLLOHOSP  0.478090 -1.6975   79.363    166
3   ASIANPAINT  1.250875 -0.1280  180.126    144
4     AXISBANK  0.726359 -1.7260  121.302    167
5   BAJAJ-AUTO  0.578410 -0.4030   77.507    134
6   BAJAJFINSV  2.150655 -1.8470  298.941    139
7   BAJFINANCE  1.223991 -1.9875  129.743    106
8   BHARTIARTL  0.744101 -1.8210  110.871    149
9         BPCL  1.000279 -1.9275  172.048    172
10   BRITANNIA  0.765955 -1.2010  120.255    157
11       CIPLA -0.092538 -1.6430  -16.009    173
12   COALINDIA -0.075500 -1.9015   -8.909    118
13    DIVISLAB  1.548772 -1.4770  196.694    127
14     DRREDDY  0.675029 -1.8920  116.105    172
15   EICHERMOT  0.853836 -1.9680  135.760    159
16      GRASIM  0.877264 -0.7700  113.167    129
17     HCLTECH  1.163217 -1.1330  187.278    161
18    HDFCBANK  0.336904 -1.5905   55.926    166
19    HDFCLIFE  0.358650 -2.1590   14.346     40
20  HEROMOTOCO  0.442850 -1.4110   70.856    160
21    HINDALCO  0.746811 -1.9960  126.211    169
22  HINDUNILVR  0.855951 -1.3140  138.664    162
23   ICICIBANK  0.651035 -1.8620   93.098    143
24  INDUSINDBK  1.731136 -1.8055  242.359    140
25        INFY  1.060845 -0.7050  164.431    155
26         ITC  0.955088 -0.7830  163.320    171
27    JSWSTEEL  0.616052 -2.3220   94.256    153
28   KOTAKBANK  3.081227 -1.6980  502.240    163
29          LT  0.808454 -1.8930  105.099    130
30        LTIM  1.675462  0.6770   65.343     39
31         M&M  0.410867 -2.0055   73.956    180
32      MARUTI  0.985383 -1.3170  126.129    128
33   NESTLEIND  0.825621  0.1680   71.829     87
34        NTPC  0.591031 -1.2850   77.425    131
35        ONGC  1.022899 -1.6755  171.847    168
36   POWERGRID  0.645080 -0.5600   72.894    113
37    RELIANCE  1.158813 -0.8205  192.363    166
38     SBILIFE  0.315911  0.1930   14.216     45
39        SBIN  0.434143 -1.9375   72.936    168
40   SUNPHARMA  1.058446 -1.2340  166.176    157
41  TATACONSUM  0.822153 -1.8880  139.766    170
42  TATAMOTORS  0.515616 -2.2745   84.561    164
43   TATASTEEL  1.313000 -2.0160  208.767    159
44         TCS  0.699583 -0.3435   92.345    132
45       TECHM  1.513340 -1.6780  155.874    103
46       TITAN  1.637911 -1.7715  239.135    146
47  ULTRACEMCO  0.870000 -0.6435  116.580    134
48         UPL  1.801654 -2.0490  275.653    153
49       WIPRO  0.801651 -1.8850  137.884    172

In [19]:
pd.DataFrame(TRADES)['returns'].agg(['mean','median','sum','count']).reset_index()

    index      returns
0    mean     1.051805
1  median    -1.694000
2     sum  7466.761000
3   count  7099.000000

In [ ]:
TRADES_WITH_TREND_CHECK = [_ for _ in TRADES]

In [20]:
all_trades = pd.DataFrame(TRADES_WITHOUT_TREND_CHECK)

In [22]:
x = all_trades[(all_trades['sell_price']=='') & (all_trades['returns']==0)].sort_values(by='buy_date', ascending=False)

x

,grade,buy_date,buy_index,sell_date,sell_index,buy_price,sell_price,returns,stock,expected_return
250,grade A,2023-09-28,5278,,5288,2970.000000,,0.0,HEROMOTOCO,2.408
2188,grade C,2023-09-28,5248,,5258,8154.350098,,0.0,ULTRACEMCO,1.167
2685,grade A,2023-09-28,5279,,5289,605.000000,,0.0,UPL,3.193
2824,grade A,2023-09-28,5929,,5939,589.950012,,0.0,SBIN,2.408
4104,grade C,2023-09-28,5931,,5941,405.350006,,0.0,WIPRO,1.167
4143,grade C,2023-09-28,1481,,1491,1289.400024,,0.0,SBILIFE,1.167
2567,grade A,2023-09-26,5929,,5939,619.799988,,0.0,TATAMOTORS,2.408
4493,grade A,2023-09-25,5275,,5285,956.349976,,0.0,ICICIBANK,2.408
1597,grade A,2023-09-22,1445,,1455,649.450012,,0.0,HDFCLIFE,2.408
3224,grade C,2023-09-22,5054,,5064,774.049988,,0.0,JSWSTEEL,1.783
5394,grade C,2023-09-20,5272,,5282,3214.350098,,0.0,ASIANPAINT,1.783
3105,grade B,2023-09-18,5920,,5930,452.049988,,0.0,ITC,2.239
953,grade B,2023-09-15,5920,,5930,4532.850098,,0.0,BRITANNIA,2.239
3591,grade B,2023-09-15,5920,,5930,352.250000,,0.0,BPCL,2.239
4858,grade B,2023-09-14,5528,,5538,1821.550049,,0.0,KOTAKBANK,1.810

In [23]:
current_price_data = {i: get_curr_price(i) for i in list(x.stock.unique())}

In [25]:
current_price_data

{'HEROMOTOCO': 2970.0,
 'ULTRACEMCO': 8154.35,
 'UPL': 605.0,
 'SBIN': 589.95,
 'WIPRO': 405.35,
 'SBILIFE': 1289.4,
 'TATAMOTORS': 614.1,
 'ICICIBANK': 942.6,
 'HDFCLIFE': 634.7,
 'JSWSTEEL': 768.1,
 'ASIANPAINT': 3170.35,
 'ITC': 440.75,
 'BRITANNIA': 4524.55,
 'BPCL': 343.95,
 'KOTAKBANK': 1733.2}

In [28]:
x['current_price'] = x['stock'].map(current_price_data)

x['current_returns'] = round(((x['current_price'] - x['buy_price'])/x['buy_price'])*100, 2)

x

,grade,buy_date,buy_index,sell_date,sell_index,buy_price,sell_price,returns,stock,expected_return,current_price,current_returns
250,grade A,2023-09-28,5278,,5288,2970.000000,,0.0,HEROMOTOCO,2.408,2970.00,0.00
2188,grade C,2023-09-28,5248,,5258,8154.350098,,0.0,ULTRACEMCO,1.167,8154.35,-0.00
2685,grade A,2023-09-28,5279,,5289,605.000000,,0.0,UPL,3.193,605.00,0.00
2824,grade A,2023-09-28,5929,,5939,589.950012,,0.0,SBIN,2.408,589.95,-0.00
4104,grade C,2023-09-28,5931,,5941,405.350006,,0.0,WIPRO,1.167,405.35,-0.00
4143,grade C,2023-09-28,1481,,1491,1289.400024,,0.0,SBILIFE,1.167,1289.40,-0.00
2567,grade A,2023-09-26,5929,,5939,619.799988,,0.0,TATAMOTORS,2.408,614.10,-0.92
4493,grade A,2023-09-25,5275,,5285,956.349976,,0.0,ICICIBANK,2.408,942.60,-1.44
1597,grade A,2023-09-22,1445,,1455,649.450012,,0.0,HDFCLIFE,2.408,634.70,-2.27
3224,grade C,2023-09-22,5054,,5064,774.049988,,0.0,JSWSTEEL,1.783,768.10,-0.77
5394,grade C,2023-09-20,5272,,5282,3214.350098,,0.0,ASIANPAINT,1.783,3170.35,-1.37
3105,grade B,2023-09-18,5920,,5930,452.049988,,0.0,ITC,2.239,440.75,-2.50
953,grade B,2023-09-15,5920,,5930,4532.850098,,0.0,BRITANNIA,2.239,4524.55,-0.18
3591,grade B,2023-09-15,5920,,5930,352.250000,,0.0,BPCL,2.239,343.95,-2.36
4858,grade B,2023-09-14,5528,,5538,1821.550049,,0.0,KOTAKBANK,1.810,1733.20,-4.85

In [29]:
x['current_returns'].sum()

-16.659999999999997